---
fixes:
  - |
    Fixed an issue where plotting Bloch spheres could cause an ``AttributeError``
    to be raised in Jupyter or when trying to crop figures down to size with
    Matplotlib 3.4.  For example, the following code would previously crash with a
    message::

      AttributeError: 'Arrow3D' object has no attribute '_path2d'

    but will now succeed with both Matplotlib 3.4 and 3.5::

      from qiskit.visualization import plot_bloch_vector
      plot_bloch_vector([0, 1, 0]).savefig("tmp.png", bbox_inches='tight')
