---
fixes:
  - |
    Fixed an issue where plotting Bloch spheres could cause an ``AttributeError``
    to be raised in Jupyter or when trying to crop figures down to size with
    Matplotlib 3.3 or 3.4 (but not 3.5).  For example, the following code would
    previously crash with a message::

      AttributeError: 'Arrow3D' object has no attribute '_path2d'

    but will now succeed with all current supported versions of Matplotlib::

      from qiskit.visualization import plot_bloch_vector
      plot_bloch_vector([0, 1, 0]).savefig("tmp.png", bbox_inches='tight')
